### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by trousers** [php-api-clients/twitter#7]
I have set this up using the example, but I get 400 bad request with no further message 

The ResponseException does not contain any info.

I don't have a callback url set up because I'm working on local, could it be that?

**Comment by mtaylor456** [comment]
Just tried a GET request using chrome postman, which works ok

**Comment by mtaylor456** [comment]
Went back to it after a few hours and it was working... vOv

**Comment by WyriHaximus** [comment]
There are a few things that can go wrong. You haven't created a config.php, the credentials in it are faulty in any way, or your time is off. Twitter's oauth only leaves a margin of error of 5 minutes on other side.

What are you trying to use the client for?

**Comment by mtaylor456** [comment]
I have it loaded in a symfony controller with my own creds. The 400 bad request disappeared a few hours later! You can close this.

**Comment by WyriHaximus** [comment]
Cheers, don't hesitate to open a new issue when problems arise :+1:
